// <auto-generated />
using ITI_Project.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITI_Project.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20240911183227_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITI_Project.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Modern clothes for men, women and kids.",
                            Name = "Clothes"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Still young with our amazing skin and hair care products.",
                            Name = "Beauty"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Don't miss AI features with our laptops, tablets and mobiles.",
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("ITI_Project.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Cotton T-Shirt for men",
                            Price = 150.40m,
                            Quantity = 10,
                            Title = "T-Shirt"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Jeans trousers for boys",
                            Price = 180.00m,
                            Quantity = 8,
                            Title = "Trousers"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Argan oil shampoo for curly hair",
                            Price = 50.70m,
                            Quantity = 7,
                            Title = "Shampoo"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Cleanser with salicylic acid for acne prone skin",
                            Price = 82.45m,
                            Quantity = 20,
                            Title = "Cleanser"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            Description = "Modern mobile with 5G network",
                            Price = 12500.00m,
                            Quantity = 11,
                            Title = "Mobile"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Description = "Laptop with 16GB Ram, 512GB SSD, RTX 3060",
                            Price = 33650.00m,
                            Quantity = 6,
                            Title = "Laptop"
                        });
                });

            modelBuilder.Entity("ITI_Project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "ahmedsalah@gmail.com",
                            FirstName = "Ahmed",
                            LastName = "Salah",
                            Password = "as1234"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "mohamedreda@gmail.com",
                            FirstName = "Mohamed",
                            LastName = "Reda",
                            Password = "mr1234"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "ziadtamer@gmail.com",
                            FirstName = "Ziad",
                            LastName = "Tamer",
                            Password = "zt1234"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "mahmoudreda@gmail.com",
                            FirstName = "Mahmoud",
                            LastName = "Reda",
                            Password = "mr1234"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "aymanmohamed@gmail.com",
                            FirstName = "Ayman",
                            LastName = "Mohamed",
                            Password = "am1234"
                        });
                });

            modelBuilder.Entity("ITI_Project.Models.Product", b =>
                {
                    b.HasOne("ITI_Project.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITI_Project.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
